xjc consMDFeNaoEncTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consmdfenaoenctiposbasico
xjc consMDFeNaoEnc_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consmdfenaoenc
xjc consReciMDFeTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consrecimdfetiposbasico
xjc consReciMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consrecimdfe
xjc consSitMDFeTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.conssitmdfetiposbasico
xjc consSitMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.conssitmdfe
xjc consStatServMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consstatservtiposbasico
xjc consStatServTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.consstatservmdfe
xjc distMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.distmdfe
xjc enviMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.envimdfe
xjc evCancMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evcancmdfe
xjc evEncMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evencmdfe
xjc eventoMDFeTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.eventomdfetiposbasico
xjc eventoMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evento
xjc evIncCondutorMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evinccondutormdfe
xjc evInclusaoDFeMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evinclusaodfemdfe
xjc evPagtoOperMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.evpagtoopermdfe
xjc leiauteDistMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.leiautedistmdfe
xjc mdfeConsultaDFeTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfeconsultadfetiposbasico
xjc mdfeConsultaDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfeconsultadfe
xjc mdfeModalAereo_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfemodalaereo
xjc mdfeModalAquaviario_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfemodalaquaviario
xjc mdfeModalFerroviario_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfemodalferroviario
xjc mdfeModalRodoviario_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfemodalrodoviario
xjc mdfeTiposBasico_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfetiposbasico
xjc mdfe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.mdfe
xjc procEventoMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.proceventomdfe
xjc procMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.procmdfe
xjc retConsMDFeNaoEnc_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retconsmdfenaoenc
xjc retConsReciMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retconsrecimdfe
xjc retConsSitMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retconssitmdfe
xjc retConsStatServMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retconsstatservmdfe
xjc retDistMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retdistmdfe
xjc retEnviMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retenvimdfe
xjc retEventoMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.reteventomdfe
xjc retMDFeConsultaDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retmdfeconsultadfe
xjc retMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.retmdfe
xjc tiposGeralMDFe_v3.00.xsd -d src -p br.inf.portalfiscal.mdfe300a.tiposgeralmdfe
xjc xmldsig-core-schema_v1.01.xsd -d src -p br.inf.portalfiscal.mdfe300a.xmldsigcoreschema